force-app/main/default/objects/Csv_Config__c/Csv_Config__c.object-meta.xml
<CustomObject>
    <description>Configuration object to store csv parsing mappings and other associated settings</description>
    <label>Csv Config</label>
    <nameField>
        <label>Csv Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Csv Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Csv_Config__c/fields/Field_Map__c.field-meta.xml
<CustomField>
    <fullName>Field_Map__c</fullName>
    <description>Comma separated field map in the form: Column1:Field1,Column2:Field2,...,ColumnN:FieldN</description>
    <inlineHelpText>Comma separated field map in the form: Column1:Field1,Column2:Field2,...,ColumnN:FieldN</inlineHelpText>
    <label>Field Map</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Csv_Config__c/fields/Has_Lookups__c.field-meta.xml
<CustomField>
    <fullName>Has_Lookups__c</fullName>
    <defaultValue>false</defaultValue>
    <description>specifies if this config has lookups to parent objects</description>
    <inlineHelpText>specifies if this config has lookups to parent objects</inlineHelpText>
    <label>Has Lookups</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Csv_Config__c/fields/Lookup_Config__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Config__c</fullName>
    <description>Field Map in the form LookupObject1:SfLookupField1:LookupField1,LookupObject2:SfLookupField2:LookupField2,... LookupObjectN:SfLookupFieldN:LookupFieldN</description>
    <inlineHelpText>Field Map in the form LookupObject1:SfLookupField1:LookupField1,LookupObject2:SfLookupField2:LookupField2,... LookupObjectN:SfLookupFieldN:LookupFieldN</inlineHelpText>
    <label>Lookup Config</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Csv_Config__c/fields/Sobject_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Api_Name__c</fullName>
    <description>The api name of the destination Sobject</description>
    <inlineHelpText>The api name of the destination Sobject</inlineHelpText>
    <label>Sobject Api Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CsvParserLwcControllerTest.cls
@suppressWarnings('pmd')
@isTest
public with sharing class CsvParserLwcControllerTest {
    
    @IsTest
    static void testGetCsvConfig(){
        try{
            Test.startTest();
            CsvParserLwcController.getCsvConfigOptions();
            Test.stopTest();

        }catch (Exception e){}
        
    }


    @IsTest
    static void testPicklistOption(){
        try{
            Test.startTest();
            CsvParserLwcController.getInteractionFieldListOptions('Account');
            //CsvParserLwcController.getInteractionFieldListOptions('Invalid Object');
            Test.stopTest();

        }catch (Exception e){}
        
    }

    @IsTest
    static void testGetAllObject(){
        try{
            Test.startTest();
            CsvParserLwcController.getAllSObjectsList();
            Test.stopTest();

        }catch (Exception e){}
        
    }

    @IsTest
    static void testGetListViewPath(){
        try{
            Test.startTest();
            CsvParserLwcController.getListViewPath('Account');
            CsvParserLwcController.getListViewPath('Bleh Bleh');
            Test.stopTest();

        }catch(Exception e){}
        
    }

    @IsTest
    static void testGetCSVHeaders(){
        try{
            Test.startTest();
            string CSV_FILE ='Name,Email,Address\nSoji,Sojman007@gmail.com,"Morohunfola Street,Opic"\nSoji2,Sojman008@gmail.com,new address';
            CsvParserLwcController.getCSVSourceFieldOptions(CSV_FILE);
            CsvParserLwcController.getCSVSourceFieldOptions('CSV_FILE');
    
           
            Test.stopTest();

        }catch (Exception e){}
        
    }

    @IsTest
    static void testGetRecordTypes(){
        try{
            Test.startTest();
            CsvParserLwcController.getRecordTypesFor('Account');
            CsvParserLwcController.getRecordTypesFor('Bleh Bleh');
            
            Test.stopTest();

        }catch (Exception e){}
        
    }



    @IsTest
    static void testSaveorUpdateConfig(){
        try{
            Test.startTest();
            
            Csv_Config__c configTest = new Csv_Config__c();
            configTest.Name ='Test Record';
            configTest.Sobject_Api_Name__c = 'Account';
            configTest.Has_Lookups__c = true;
            configTest.Field_Map__c = 'Name:Name;Email:Email__c,Address:Residential_Address__c';
            configTest.Lookup_Config__c = 'Test:Test:Test';
            configTest.Active__c = true;
            configTest.Has_Lookups__c = false;
    
    
            LwcDtos.CsvConfigurationRecord configRecord = new LwcDtos.CsvConfigurationRecord();
            LwcDtos.CsvConfigurationRecord configRecord2 = new LwcDtos.CsvConfigurationRecord(configTest);
            CsvParserLwcController.saveOrUpdateConfig(configRecord);
            CsvParserLwcController.saveOrUpdateConfig(configRecord2);
    
            Test.stopTest();

        }catch (Exception e){

        }
        
    }

    @IsTest
    static void getTestCsvConfig(){
        try{
            Test.startTest();
            CsvParserLwcController.getCsvConfig('fakeId');
            Test.stopTest();

        }catch(Exception e){

        }
        
    }


    @IsTest
    static void testConvertDataFromCsv(){
        try{
            Test.startTest();
            string CSV_FILE ='Name,Email,Address\nSoji,Sojman007@gmail.com,"Morohunfola Street,Opic"\nSoji2,Sojman008@gmail.com,new address';
            map<string,string> fieldMap = new Map<String,String>{};
            fieldMap.put('Name', 'Name');
            fieldMap.put('Email', 'Email__c');
            fieldMap.put('Address', 'Residential_Address__c');
    
            List<LwcDtos.LookUpConfig> lcfs = new List<LwcDtos.LookUpConfig>();
    
            LwcDtos.LookUpConfig lcf = new LwcDtos.LookUpConfig();
            lcf.lookupField = 'Test';
            lcf.lookupObject = 'Account';
            lcf.sflookupField ='Id';
    
            lcfs.add(lcf);
            CsvParserLwcController.convertDataFromCsv(CSV_FILE, fieldMap, lcfs, 'Account', 'null');
            
            Test.stopTest();

        }catch (Exception e){

        }
        
    }
}