force-app/main/default/objects/Csv_Config__c/Csv_Config__c.object-meta.xml
<CustomObject>
    <description>Configuration object to store csv parsing mappings and other associated settings</description>
    <label>Csv Config</label>
    <nameField>
        <label>Csv Config Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Csv Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Csv_Config__c/fields/Field_Map__c.field-meta.xml
<CustomField>
    <fullName>Field_Map__c</fullName>
    <description>Comma separated field map in the form: Column1:Field1,Column2:Field2,...,ColumnN:FieldN</description>
    <inlineHelpText>Comma separated field map in the form: Column1:Field1,Column2:Field2,...,ColumnN:FieldN</inlineHelpText>
    <label>Field Map</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Csv_Config__c/fields/Has_Lookups__c.field-meta.xml
<CustomField>
    <fullName>Has_Lookups__c</fullName>
    <defaultValue>false</defaultValue>
    <description>specifies if this config has lookups to parent objects</description>
    <inlineHelpText>specifies if this config has lookups to parent objects</inlineHelpText>
    <label>Has Lookups</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Csv_Config__c/fields/Lookup_Config__c.field-meta.xml
<CustomField>
    <fullName>Lookup_Config__c</fullName>
    <description>Field Map in the form LookupObject1:SfLookupField1:LookupField1,LookupObject2:SfLookupField2:LookupField2,... LookupObjectN:SfLookupFieldN:LookupFieldN</description>
    <inlineHelpText>Field Map in the form LookupObject1:SfLookupField1:LookupField1,LookupObject2:SfLookupField2:LookupField2,... LookupObjectN:SfLookupFieldN:LookupFieldN</inlineHelpText>
    <label>Lookup Config</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Csv_Config__c/fields/Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Id__c</fullName>
    <description>The target record type Id for the records being created.</description>
    <label>Record Type Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Csv_Config__c/fields/Sobject_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Api_Name__c</fullName>
    <description>The api name of the destination Sobject</description>
    <inlineHelpText>The api name of the destination Sobject</inlineHelpText>
    <label>Sobject Api Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LwcDtos.cls
public without sharing class LwcDtos {
    
    public class Option{
        @AuraEnabled
        public string name {get;set;}
        @AuraEnabled
        public string value {get;set;}

        public Option(string n , string v){
            name = n;
            value = v;
        }
    }

    public class LookUpConfig{
        @auraEnabled
        public string lookupObject {get;set;}
        @auraEnabled
        public string sflookupField {get;set;}
        @auraEnabled
        public string lookupField {get;set;}
    }
    
    public class FieldMap {
        @auraEnabled
        public string source {get;set;}
        @auraEnabled
        public string destination {get;set;}
    }
    public class CsvConversionResult{
        @auraEnabled
        public boolean success {get;set;}

        @auraEnabled
        public List<Sobject> records {get;set;}


        public CsvConversionResult setSuccess(boolean suc){
            success = suc;
            return this;
        }
        public CsvConversionResult setRecords(List<Sobject> rec){
            records = new List<Sobject>(rec);
            return this;
        }
    }

    public class CsvConfigurationRecord{
        @auraEnabled
        public string configId {get;set;}
        @auraEnabled
        public string recordTypeId {get;set;}
        @auraEnabled
        public string destinationObject {get;set;}
        @auraEnabled
        public boolean hasLookup {get;set;}
        @auraEnabled
        public string configName {get;set;}
        @auraEnabled
        public List<LwcDtos.LookupConfig> lookupConfigs {get;set;}
        @auraEnabled
        public List<LwcDtos.FieldMap> fieldMaps {get;set;}

        public CsvConfigurationRecord(){
            configId ='';
            configName='New Config - ' + String.valueOfGmt(Datetime.now());
            destinationObject ='';
            hasLookup = false;
            lookupConfigs = new List<LwcDtos.LookUpConfig>();
            fieldMaps = new List<LwcDtos.FieldMap>();
        }

        public CsvConfigurationRecord(Csv_Config__c csvConfig){
            this.configId = csvConfig.Id;
            this.recordTypeId = csvConfig.Record_Type_Id__c;
            this.destinationObject = csvConfig.Sobject_Api_Name__c;
            this.hasLookup = csvConfig.Has_Lookups__c;
            this.configName = csvConfig.Name;
            lookupConfigs = new List<LwcDtos.LookUpConfig>();
            fieldMaps = new List<LwcDtos.FieldMap>();
            if(csvConfig.Field_Map__c != null){
                loadFieldMap(csvConfig.Field_Map__c);
            }
            if(csvConfig.Lookup_Config__c != null){
                loadLookupConfigs(csvConfig.Lookup_Config__c);
            }



        }

        public Csv_Config__c toRecord(){
            Csv_Config__c configR = new Csv_Config__c(
                Sobject_Api_Name__c = destinationObject,
                Has_Lookups__c = hasLookup,
                Name = configName
            );
            if(String.isNotBlank(configId)){
                configR.Id = configId;
            }
            if(String.isNotBlank(recordTypeId)){
                configR.Record_Type_Id__c = recordTypeId;
            }

            string lookUpConfigString = '';
            string fieldMapString ='';

            for(LwcDtos.LookUpConfig lcfg : lookupConfigs ){
                lookUpConfigString += String.join(new List<String>{lcfg.lookupObject,lcfg.sflookupField,lcfg.lookupField },':')+',';
            }
            lookUpConfigString = lookUpConfigString.removeEnd(',');
            configR.Lookup_Config__c = lookUpConfigString;
            for(LwcDtos.FieldMap fMap : fieldMaps ){
                fieldMapString += String.join(new List<String>{fMap.source , fMap.destination}, ':') + ',';
            }
            fieldMapString = fieldMapString.removeEnd(',');
            configR.field_map__c = fieldMapString;

            return configR;


        }

        private void loadFieldMap(string fieldMapString){
            for(string fieldMap : fieldMapString.split(',')){
                LwcDtos.Fieldmap fMap = new LwcDtos.FieldMap();
                fMap.destination = fieldMap.substringAfter(':').trim();
                fMap.source = fieldMap.substringBefore(':').trim();
                fieldMaps.add(fMap);
            }
        }

        private void loadLookupConfigs(string configString){
            for(string config : configString.split(',')){
                List<string> splitConfig = config.split(':');
                LwcDtos.LookUpConfig lookUpConfigObj = new LwcDtos.LookUpConfig();
                lookUpConfigObj.lookupObject = splitConfig[0];
                lookUpConfigObj.sflookupField = splitConfig[1];
                lookUpConfigObj.lookupField = splitConfig[2];
                lookupConfigs.add(lookUpConfigObj);
            }
        }





    }


}