force-app/main/default/objects/Csv_Parser_Log__c/Csv_Parser_Log__c.object-meta.xml
<CustomObject>
    <description>logs to store information about the csv parser</description>
    <label>Csv Parser Log</label>
    <nameField>
        <label>Csv Parser Logs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Csv Parser Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Csv_Parser_Log__c/fields/Log_Lines_Formatted__c.field-meta.xml
<CustomField>
    <fullName>Log_Lines_Formatted__c</fullName>
    <description>Formatted Log Lines per operation</description>
    <label>Log Lines Formatted</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Csv_Parser_Notification__e/Csv_Parser_Notification__e.object-meta.xml
<CustomObject>
    <description>Delivers a notification related to the CSV Parser operation</description>
    <label>Csv Parser Notification</label>
    <pluralLabel>Csv Parser Notifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Csv_Parser_Notification__e/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>valid values are &quot;BATCH_START&quot;,&quot;BATCH_END&quot;, &quot;EXTRACT_START&quot;,&quot;EXTRACT_END&quot;,&quot;CONVERT_START&quot;,&quot;CONVERT_END&quot;</description>
    <label>Event Type</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Csv_Parser_Notification__e/fields/Message_Json__c.field-meta.xml
<CustomField>
    <fullName>Message_Json__c</fullName>
    <description>notification as JSON message</description>
    <label>Message_Json</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Csv_Parser_Save_Job__c/Csv_Parser_Save_Job__c.object-meta.xml
<CustomObject>
    <description>Stores the job details of the CSV parser job</description>
    <label>Csv Parser Save Job</label>
    <nameField>
        <label>Csv Parser Save Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Csv Parser Save Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Csv_Parser_Save_Job__c/fields/Record_Ids__c.field-meta.xml
<CustomField>
    <fullName>Record_Ids__c</fullName>
    <description>Record Ids of records Processed by this Job</description>
    <inlineHelpText>Record Ids of records Processed by this Job</inlineHelpText>
    <label>Record Ids</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Csv_Parser_Save_Job__c/fields/Sobject_Type_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Sobject_Type_Api_Name__c</fullName>
    <description>The Api Name of the Sobject Type that was mapped</description>
    <inlineHelpText>The Api Name of the Sobject Type that was mapped</inlineHelpText>
    <label>Sobject Type Api Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Csv_Parser_Save_Job__c/fields/Total_Number_Of_Records__c.field-meta.xml
<CustomField>
    <fullName>Total_Number_Of_Records__c</fullName>
    <description>Total number of records processed by this Job</description>
    <label>Total Number Of Records</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CsvParserBatchInsertApex.cls
public without sharing class CsvParserBatchInsertApex implements Database.Batchable<CsvParserRecordWrapper>, Database.Stateful {
    

    private List<CsvParserRecordWrapper> recordsToSave = new List<CsvParserRecordWrapper>();
    private integer insertedSize = 0;
    private Csv_Parser_Save_Job__c  parserJob;
    private string parserLogId ='';
    map<integer ,List<String>> errors = new Map<integer, List<String>>();
    private static final string BATCH_RESULT_LOGLINE = '<p><strong>BATCH RECORD SAVE RESULTS</strong></p><ul><li><i>Number Of Successfully Saved Records : {0} </i> </li><li><i>Number Of Failed Records : {1} </i> </li></ul>';

    
    public CsvParserBatchInsertApex(List<CsvParserRecordWrapper> records , string parserLogId) {
        recordsToSave.addAll(records);
        this.parserLogId = parserLogId;
        parserJob = new Csv_Parser_Save_Job__c();
        parserJob.Name = UserInfo.getFirstName() + ' ' + UserInfo.getLastName() + ' | Batch Save Job  ' + String.valueOfGmt(Datetime.now().addHours(1));
        parserJob.Record_Ids__c ='';
        parserJob.Sobject_Type_Api_Name__c = records[0].getRecord().getSObjectType().getDescribe().getName();
        insert parserJob;
    }

    public Iterable<CsvParserRecordWrapper> start(Database.BatchableContext cont){
        List<Csv_Parser_Notification__e> platformEvents = new List<Csv_Parser_Notification__e>();
        Csv_Parser_Notification__e event = new Csv_Parser_Notification__e(
            Event_Type__c ='BATCH_START'
        );
        platformEvents.add(event);
        EventBus.publish(platformEvents);

        return this.recordsToSave;
    }

    public void execute(Database.BatchableContext ctx , List<CsvParserRecordWrapper> scope){
        try{
            map<integer, Sobject> toSaveMap = CsvParserRecordWrapper.listToRecordmap(scope);
            map<integer, CsvParserRecordWrapper> toSaveWrapperMap = CsvParserRecordWrapper.listToWrappermap(scope);
            List<Sobject> toSave = toSaveMap.values();
            List<Database.SaveResult> saveResults =   Database.insert(toSave, false, System.AccessLevel.USER_MODE);
            handleDatabaseSaveResults(saveResults, toSaveWrapperMap);
            
            
        }catch(exception e){
            List<Csv_Parser_Notification__e> platformEvents = new List<Csv_Parser_Notification__e>();
            map<string,object> errorMessage = new map<string,Object>{'error'=> e.getMessage()};
            Csv_Parser_Notification__e event = new Csv_Parser_Notification__e(
                Event_Type__c ='BATCH_ERROR', Message_Json__c = JSON.serialize(errorMessage)
            );
            platformEvents.add(event);
            EventBus.publish(platformEvents);
        }
    }


    private string getErrorDump(){
        string errorDump = '';
        for(integer index : errors.keySet()){
            errorDump += '\nDb Errors At Row : ' + index + '\n';
            errorDump += String.join(errors.get(index),'' + '\n');
        }

        return errorDump;


    }

    private void handleDatabaseSaveResults(List<Database.SaveResult> saveResults, map<integer, CsvParserRecordWrapper> toSaveWrapperMap){
        integer successSize = 0;
        integer index = 0;
        integer failedSize = 0;
        List<integer> indices = new List<integer>(toSaveWrapperMap.keySet());
        for(Database.SaveResult result :saveResults){ 
            if(result.success){
                successSize +=1;
                parserJob.Record_Ids__c += result.id  + ',';
            }else{
                failedSize += 1;
                List<string> errList = new List<String>();
                for(Database.Error error  : result.getErrors()){
                    errList.add('   - ' + error.getMessage() + '. Fields [ ' + String.join(error.getFields() ,', ') + ' ]');
                }
                errors.put(indices.get(index), errList);
            }
            index += 1;
        }
        insertedSize += successSize;

        if(failedSize > 0){
            List<Csv_Parser_Notification__e> platformEvents = new List<Csv_Parser_Notification__e>();
            map<string,object> errorMessage = new map<string,Object>{'failedRecords'=> this.errors.size() , 'passedRecords' => this.insertedSize};
            
            Csv_Parser_Notification__e event = new Csv_Parser_Notification__e(
                Event_Type__c ='BATCH_PROGRESS', Message_Json__c = JSON.serialize(errorMessage)
            );
            platformEvents.add(event);
            EventBus.publish(platformEvents);

        }
    }


    public void finish(Database.BatchableContext ctx){
        
        SobjectDomainService service = new SobjectDomainService('Csv_Parser_Log__c');
        Csv_Parser_Log__c log = String.isNotBlank(parserLogId) ?  (Csv_Parser_Log__c)service.getRecordWhereIdIs(parserLogId) : new Csv_Parser_Log__c();
       
        if(String.isBlank(parserLogId)){
            log.Name = UserInfo.getFirstName() + ' ' + UserInfo.getLastName() + ' | CSV PARSER OPERATION RESULTS ' + Datetime.now().addHours(1);
        }
        string formattedString =  String.format(BATCH_RESULT_LOGLINE, new List<Integer>{ this.insertedSize , errors.size() });
        log.Log_Lines_Formatted__c = String.isNotBlank(log.Log_Lines_Formatted__c) ? (log.Log_Lines_Formatted__c + '\n' + formattedString) : formattedString;
        StanbicIbtcCompliantDml.dmlUpsert(new List<Csv_Parser_Log__c>{log});
        
        if(errors.size() > 0){
            Attachment errorAttachmentFile = new Attachment();
            errorAttachmentFile.Name = log.Name + ' ERROR LOG FILE';
            errorAttachmentFile.ParentId = log.Id;
            errorAttachmentFile.ContentType = 'text/plain';
            errorAttachmentFile.Body = Blob.valueOf(getErrorDump());
            StanbicIbtcCompliantDml.dmlInsert(new List<Attachment>{errorAttachmentFile});
        }

        List<Csv_Parser_Notification__e> platformEvents = new List<Csv_Parser_Notification__e>();
        Csv_Parser_Notification__e event = new Csv_Parser_Notification__e(
            Event_Type__c ='BATCH_END' , Message_JSON__c = JSON.serialize(new map<string,Object>{'success' => this.insertedSize ,'failed' => errors.size()})
        );
        platformEvents.add(event);
        
        EventBus.publish(platformEvents);
        parserJob.Total_Number_Of_Records__c = this.insertedSize;
        update parserJob;
    }
}